config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: :new
  end

  resources :albums, only: [:create, :edit, :show, :update, :destroy]
end

app/models/album.rb
class Album < ApplicationRecord

  belongs_to :band,
    foreign_key: :band_id,
    class_name: 'Band'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true

  has_many :albums,
    foreign_key: :band_id,
    class_name: 'Album'
  

end

app/models/user.rb
class User < ApplicationRecord

  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  after_initialize :ensure_session_token

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.is_password?(password)
    return user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    bc_password = BCrypt::Password.new(self.password_digest)
    bc_password.is_password?(password)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    return self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      redirect_to album_url(album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    if @album.update_attributes(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to bands_url
  end

  private
  def album_params
    params.require(:album).permit(:title, :year, :band_id, :studio_album)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

  def require_no_user!
    if logged_in?
      redirect_to user_url(@current_user)
    end
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :show
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :show
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private
  def band_params
    params.require(:band).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_action :require_no_user!, only: [:create, :new]

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user
      log_in_user!(user)
      redirect_to user_url(user)
    else
      flash.now[:errors] = ['Invalid credentials!']
      render :new
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_no_user!, only: [:create, :new]

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find_by(session_token: session[:session_token])
    render :show
  end

  private
  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bands/index.html.erb
<h1>All The Bands!</h1>

<ul><% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><%= band.name %></a></li>
  <% end %>
</ul>
  

app/views/bands/new.html.erb
<h1>Add A Band!</h1>

<form action="<%= bands_url %>" method = "POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="text"
    name="band[name]"
    id="band_name"
    value="<%= @band.name %>">
  <br>
  <input type="submit">

</form>

app/views/bands/show.html.erb
<h1><%= @band.name %></h1>
<h3>Edit This Band Name:</h3>
<form action="<%= band_url(@band) %>" method = "POST">
  <input type="hidden" name="_method" value="PATCH">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="text"
    name="band[name]"
    id="band_name"
    value="<%= @band.name %>">
  <br>
  <input type="submit">

</form>

<h3>Delete This Band:</h3>
<form action="<%= band_url(@band) %>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <input type="submit" value="Delete This Band">
  
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <style>
      body {
        font-family: 'Balsamiq Sans', cursive;
      }

      .nav{
        display: flex;
        float: right;
        background-color: pink;
        border-radius: 1px;
        text-decoration: none;
      }
      .sub_title {
        display: flex;
        flex-direction: column;
        align-items: center;
      }
      .form {
        display: flex;
        flex-direction: column;
        align-items: center;
      }
    </style>
    
    <title>MyMusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="main">
    <h1 class="title">Welcome to My Music App!</h1>
    <% if logged_in? %>
      <h2>Hey there, <%= current_user.email %></h2>
      <form action="<%= session_url %>" method="POST">
        <input type="hidden" name="_method" value="DELETE">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

        <input type="submit" value="Logout">
      </form>
    <% else %>
      <br>
      <br>
      <a class="nav" href="<%= new_session_url %>">Login</a>
      <br>
      <a class="nav" href="<%= new_user_url %>">Sign Up</a>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form class="form" action="<%= users_url %>" method="POST">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

    <label>Email:
    <br>
        <input type="text" name="user[email]">
    </label>
    <br>
    <label for="password">Password:</label>
        <input type="password" name="user[password]" id="password">

    <input type="submit" value="Sign Up">
</form>